<?php

namespace AppBundle\Repository;

/**
 * BlogControllerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogControllerRepository extends \Doctrine\ORM\EntityRepository
{
}
